local transf = require "transf"
local vec3 = require "vec3"
local modulesutil = require "modulesutil"
local trainstationutil = require "modules/trainstationutil"
local constructionutil = require "constructionutil"

local cargoCapacity = 40
local passengerCapacity = 0

--Begin Generated
local generatedData = {
	["cargo_station_main_2_assets_1"] = {
		models = {
			["asset/ground/barrel_steel.mdl"] = {
				{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, -6.50000, -2.48000, 0.80000, 1.00000 },
				{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, -0.15000, -4.40000, 0.80000, 1.00000 },
				{ 0.77051, 0.63742, 0.00000, 0.00000, -0.62395, 0.75423, 0.20450, 0.00000, 0.13035, -0.15757, 0.97887, 0.00000, -1.09000, -4.39500, 0.87500, 1.00000 },
			},
			["asset/ground/container_waste2.mdl"] = {
				{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, -6.74000, -16.90000, -0.00000, 1.00000 },
			},
			["asset/industry/cardboard_box_01.mdl"] = {
				{ -0.65433, -0.02971, 0.00000, 0.00000, 0.02971, -0.65433, 0.00000, 0.00000, 0.00000, 0.00000, 0.65500, 0.00000, 4.32500, -16.41500, 0.00000, 1.00000 },
				{ -0.79404, -0.23671, 0.00000, 0.00000, 0.23671, -0.79404, 0.00000, 0.00000, 0.00000, 0.00000, 0.82857, 0.00000, 4.86500, -16.44000, 0.00000, 1.00000 },
			},
			["station/rail/asset/cargo_lamps.mdl"] = {
				{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 5.00000, -22.00000, 0.00000, 1.00000 },
				{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, -5.00000, -22.00000, 0.00000, 1.00000 },
			},
			["station/rail/asset/cargo_name_board.mdl"] = {
				{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, -4.00000, -18.50000, 0.00000, 1.00000 },
			},
			["station/rail/asset/cargo_speakers.mdl"] = {
				{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 2.76000, -3.50000, 0.80000, 1.00000 },
			},
		},
	},
}
--End Generated

function data()

return { 
	cost = {
		price = 20000,
	},
	category = {
		categories = { "cargo buildings", },
	},
	description = {
		name = _("Medium main building"),
		description = _("Medium main building with street access for cargo stations. Provides capacity for 40 cargo items."),
		icon = "ui/construction/station/rail/modular_station/main_building_2_cargo.tga",
	}, 
	availability = {
		yearFrom = 0,
	},
	type = "rail_main_building_size2",
	order = {
		value = 940,
	},
	metadata = {
		era = 5,
		level =2,
		span = {1, 2},
		moreCapacity = {
			cargo = cargoCapacity,
			passenger = passengerCapacity
		},
		snapPoint = transf.rotZTransl(-math.pi / 2, vec3.new(-20, 0, 0))
	},
	
	updateFn = function(result, transform, tag, slotId, addModuleFn, params)
		local config = {
			extend = { 11, -11, 0, -23, 4, 0 },
			main = "station/rail/cargo/station_2_main.mdl",
			con_left = {"station/rail/cargo/station_2_main_end_l.mdl","station/rail/cargo/station_2_main_con_l_2.mdl","station/rail/cargo/station_2_main_con_l_2.mdl",},
			con_right = {"station/rail/cargo/station_2_main_end_r.mdl","station/rail/cargo/station_2_main_con_r_2.mdl","station/rail/cargo/station_2_main_con_r_2.mdl",},
			end_left = "station/rail/cargo/station_2_main_end_l.mdl",
			end_right = "station/rail/cargo/station_2_main_end_r.mdl",
			slotIdOffset = 0,
			translationY = 0,
		}
	
		local tran = trainstationutil.MakeMainBuildingModule(result, transform, tag, slotId, addModuleFn, params, config)
		constructionutil.addModels(generatedData["cargo_station_main_2_assets_1"], result.models, tran, tag)
	end,
	
	getModelsFn = function()
		
		local result = {
			{ 
				id = "station/rail/cargo/station_2_main.mdl",
				transf = transf.rotZTransl(math.rad(-90), vec3.new(15,0,0)),
			},
			{ 
				id = "station/rail/cargo/station_2_main_end_l.mdl",
				transf = transf.rotZTransl(math.rad(-90), vec3.new(15,0,0)),
			},
			{ 
				id = "station/rail/cargo/station_2_main_end_r.mdl",
				transf = transf.rotZTransl(math.rad(-90), vec3.new(15,0,0)),
			},
		}
		
		return result
	end
}

end
