local transf = require "transf"
local vec3 = require "vec3"
local modulesutil = require "modulesutil"
local constructionutil = require "constructionutil"

--Begin Generated
--End Generated
local generatedData = {
	["era_b_perron_5_name_board"] = {
		models = {
			["station/rail/asset/era_b_name_board.mdl"] = {
				{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 20.00000, -0.00000, 0.80000, 1.00000 },
			},
		},
	},
	["era_b_1"] = {
		models = {
			["station/rail/asset/era_b_sign_nr_l.mdl"] = {
				{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 34.00000, 0.00000, 0.00000, 1.00000 },
			},
		},
	},
	["era_b_2"] = {
		models = {
			["station/rail/asset/era_b_sign_nr_r.mdl"] = {
				{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 6.00000, 0.00000, 0.00000, 1.00000 },
			},
		},
	},
	["era_b_perron_5_assets_1"] = {
		models = {
			["station/rail/asset/era_b_double_chair.mdl"] = {
				{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 10.00000, 0.00000, 0.80000, 1.00000 },
				{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 30.00000, 0.00000, 0.80000, 1.00000 },
			},
			["station/rail/asset/era_b_trashcan.mdl"] = {
				{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 8.00000, 0.00000, 0.80000, 1.00000 },
				{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 32.00000, 0.00000, 0.80000, 1.00000 },
			},
			["street/street_light_us_a.mdl"] = {
				{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 12.00000, 0.00000, 0.80000, 1.00000 },
				{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 28.00000, 0.00000, 0.80000, 1.00000 },
			},
		},
	},
}

function data()

local function GetModelsConfig() 
	return {
		perron = "station/rail/era_b/perron_5.mdl",
		endPerron = "station/rail/era_b/perron_5_end.mdl",
		perronRoof = "station/rail/era_b/perron_5_roof.mdl",
		endPerronRoof = "station/rail/era_b/perron_5_roof_end.mdl",
		era = 1,
	}
end

return { 
	availability = {
		yearFrom = 1920,
		yearTo = 1980,
	},
	category = {
		categories = { "platforms", },
	},
	cost = {
		price = 18000,
	},
	description = {
		name = _("Passenger platform"),
		description = _("A platform for passengers."),
		icon = "ui/construction/station/rail/modular_station/platform_passenger_era_b.tga",
	},
	-- buildMode = "MULTI",
	type = "passenger_platform",
	order = {
		value = 710,
	},
	metadata = {
		platform = true,
		passenger_platform = true,
	},
	
	updateFn = function(result, transform, tag, slotId, addModelFn)
		local faces = {
			{2.5,  -20.0, 0.0, 1.0},
			{2.5,  20.0,  0.0, 1.0},
			{-2.5, 20.0,  0.0, 1.0},
			{-2.5, -20.0, 0.0, 1.0},
		}
		modulesutil.TransformFaces(transform, faces)
		local faces2 = { type = "EQUAL", faces = {  faces } }
		table.insert(result.terrainAlignmentLists, faces2)
		
		table.insert(result.colliders, {
			type = "BOX",
			transf = transform,
			params = {
				halfExtents = { 2.5, 20, 2 },
			}
		})
		
		table.insert(result.groundFaces, {  
			face = faces,
			modes = {
				{
					type = "FILL",
					key = "shared/gravel_03.gtex.lua"
				},
				{
					type = "STROKE_OUTER",
					key = "street_border.lua"
				},
			},
		})
		
		local coords = result.GetCoord(slotId)
		local i = coords[1]
		local j = coords[2]
		
		local hasStairs = result.GetPlatformAddonAt(i, j) and result.GetPlatformAddonAt(i, j).metadata.underground
		
		if not hasStairs then
			result.models[#result.models + 1] = { 
				id = "station/rail/era_a/tn_underground_connection.mdl",
				transf = transf.mul(transform, transf.transl(vec3.new(0, 0, 0))),
				tag = tag
			}
			
			local modelsConfig = GetModelsConfig()
			addModelFn(modelsConfig.perron, transf.rotZTransl(math.rad(90), vec3.new(0, -20, 0)), "perron" .. i .. "_" .. j)
			--addModelFn(modelsConfig.perronRoof, transf.rotZTransl(math.rad(90), vec3.new(0, -20, 0)))
			
			local tran = transf.mul(transform, transf.rotZTransl(math.rad(90), vec3.new(0, -20, 0)))
			
			local num1 = #result.models
			result.addPlatformCallback(i, j, function(left, n, station)
				local ns = tostring(n)
				if left then
					result.labelText[num1 + 1] = {ns,ns}
				else
					result.labelText[num1 + 0] = {ns,ns}
				end
				local stationS = tostring(station)
				result.labelText[num1 + 2] = {stationS,stationS}
			end)
			constructionutil.addModels(generatedData["era_b_1"], result.models, tran, tag)
			constructionutil.addModels(generatedData["era_b_2"], result.models, tran, tag)
			constructionutil.addModels(generatedData["era_b_perron_5_name_board"], result.models, tran, tag)
			constructionutil.addModels(generatedData["era_b_perron_5_assets_1"], result.models, tran, tag)
			
			local nextM = result.GetModuleAt(i,j-1)
			local ca =  (nextM and (nextM.metadata.passenger_platform or nextM.metadata.cargo_platform)) or  result.connector[1000 * i + 100 * (j-1) + 7]
			if not ca then
				addModelFn(modelsConfig.endPerron, transf.rotZTransl(math.rad(-90), vec3.new(0, -20, 0)))
				--addModelFn(modelsConfig.endPerronRoof, transf.rotZTransl(math.rad(-90), vec3.new(0, -20, 0)))
			end
			local prevM = result.GetModuleAt(i,j+1)
			local cb = (prevM and (prevM.metadata.passenger_platform or prevM.metadata.cargo_platform)) or  result.connector[1000 * i + 100 * (j+1) + 0]
			if not cb then
				addModelFn(modelsConfig.endPerron, transf.rotZTransl(math.rad(90), vec3.new(0, 20, 0)))
				--addModelFn(modelsConfig.endPerronRoof, transf.rotZTransl(math.rad(90), vec3.new(0, 20, 0)))
			end
		end
	end,
	
	getModelsFn = function()
		local modelsConfig = GetModelsConfig()
		local result = {
			{ 
				id = modelsConfig.perron,
				transf = transf.rotZTransl(math.rad(90), vec3.new(0,-20,0)),
			},
			{ 
				id = modelsConfig.endPerron,
				transf = transf.rotZTransl(math.rad(-90), vec3.new(0,-20,0)),
			},
			{ 
				id = modelsConfig.endPerron,
				transf = transf.rotZTransl(math.rad(90), vec3.new(0,20,0)),
			},
			-- { 
				-- id = modelsConfig.perronRoof,
				-- transf = transf.rotZTransl(math.rad(90), vec3.new(0,-20,0)),
			-- },
			-- { 
				-- id = modelsConfig.endPerronRoof,
				-- transf = transf.rotZTransl(math.rad(-90), vec3.new(0,-20,0)),
			-- },
			-- { 
				-- id = modelsConfig.endPerronRoof,
				-- transf = transf.rotZTransl(math.rad(90), vec3.new(0,20,0)),
			-- },
		}
		
		return result
	end
}

end
