local transf = require "transf"
local vec3 = require "vec3"
local modulesutil = require "modulesutil"
local trainstationutil = require "modules/trainstationutil"

function data()

return { 
	availability = {
		yearFrom = 1925,
		yearTo = 0,
	},
	cost = {
		price = 40000,
	},
	category = {
		categories = { "tracks", },
	},
	description = {
		name = _("High-speed tracks with catenary"),
		description = _("Specialized tracks with catenary for higher speeds."),
		icon = "ui/construction/station/rail/modular_station/high_speed_catenary.tga"
	},
	-- buildMode = "MULTI",
	type = "track",
	order = {
		value = 360,
	},
	metadata = {
		track = true,
	},
	
	updateFn = function(result, transform, tag, slotId, addModuleFn, params)
		trainstationutil.makeTrack(result, transform, tag, slotId, addModuleFn, params, 4)
	end,
	
	getModelsFn = function()
		
		local result = {
		}
		
		return result
	end
}

end
