function data()
    return {
        "Jalan Sudirman",
        "Jalan Thamrin",
        "Jalan Gatot Subroto",
        "Jalan Rasuna Said",
        "Jalan Merdeka",
        "Jalan Diponegoro",
        "Jalan Ahmad Yani",
        "Jalan Pahlawan",
        "Jalan Gajah Mada",
        "Jalan Raden Saleh",
        "Jalan Sisingamangaraja",
        "Jalan Imam Bonjol",
        "Jalan Panglima Polim",
        "Jalan KH. Hasyim Ashari",
        "Jalan Kertajaya",
        "Jalan Pemuda",
        "Jalan Pattimura",
        "Jalan Diponegoro",
        "Jalan Teuku Umar",
        "Jalan Pemuda",
        "Jalan Slamet Riyadi",
        "Jalan A. Yani",
        "Jalan Ahmad Dahlan",
        "Jalan Pramuka",
        "Jalan Letjen Suprapto",
        "Jalan Jenderal Basuki Rahmat",
        "Jalan Gunung Sahari",
        "Jalan Mangga Dua",
        "Jalan Kebon Jeruk",
        "Jalan Pangeran Antasari",
        "Jalan Senopati",
        "Jalan Mangga Besar",
        "Jalan Veteran",
        "Jalan Mayjen Sungkono",
        "Jalan Dharmawangsa",
        "Jalan Haji Agus Salim",
        "Jalan Budi Utomo",
        "Jalan Brawijaya",
        "Jalan Kyai Tapa",
        "Jalan Majapahit",
        "Jalan Trunojoyo",
        "Jalan Hayam Wuruk",
        "Jalan Ahmad Ibrahim",
        "Jalan Soekarno-Hatta",
        "Jalan Moh. Toha",
        "Jalan Taman Sari",
        "Jalan Margonda Raya",
        "Jalan Otto Iskandardinata",
        "Jalan Dr. Wahidin",
        "Jalan Dr. Sutomo",
        "Jalan Jendral Sudirman",
        "Jalan Letda Kajeng",
    }
end
