function data()
    return {
        "Banda Aceh",
        "Langsa",
        "Lhokseumawe",
        "Sabang",
        "Subulussalam",
        "Medan",
        "Binjai",
        "Padang Sidempuan",
        "Tanjung Balai",
        "Tebing Tinggi",
        "Padang",
        "Bukit Tinggi",
        "Payakumbuh",
        "Sawahlunto",
        "Solok",
        "Pekanbaru",
        "Dumai",
        "Jambi",
        "Sungai Penuh",
        "Palembang",
        "Lubuklinggau",
        "Pagar Alam",
        "Prabumulih",
        "Bengkulu",
        "Bandar Lampung",
        "Metro",
        "Pangkal Pinang",
        "Tanjung Pinang",
        "Batam",
        "Jakarta",
        "Bandung",
        "Cimahi",
        "Tasikmalaya",
        "Banjar",
        "Semarang",
        "Salatiga",
        "Pekalongan",
        "Tegal",
        "Magelang",
        "Surakarta",
        "Yogyakarta",
        "Surabaya",
        "Kediri",
        "Blitar",
        "Madiun",
        "Mojokerto",
        "Pasuruan",
        "Probolinggo",
        "Malang",
        "Serang",
        "Cilegon",
        "Tangerang",
        "South Tangerang",
        "Denpasar",
        "Mataram",
        "Bima",
        "Kupang",
        "Pontianak",
        "Singkawang",
        "Palangka Raya",
        "Banjarmasin",
        "Banjarbaru",
        "Samarinda",
        "Balikpapan",
        "Bontang",
        "Tanjung Selor",
        "Tarakan",
        "Manado",
        "Bitung",
        "Kotamobagu",
        "Tomohon",
        "Gorontalo",
        "Palu",
        "Makassar",
        "Parepare",
        "Palopo",
        "Kendari",
        "Bau-Bau",
        "Ambon",
        "Tual",
        "Jayapura",
        "Sorong"
    }
end
